project:
  type: website
  output-dir: docs

website:
  title: "HH"
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: About
      - papers.qmd
      - teaching.qmd
      - projects.qmd
      - packages.qmd
    right:
      - icon: github
        href: https://github.com/heike
        aria-label: GitHub

format:
  html:
    theme: darkly
    css: styles.css
    toc: false



